apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
    - name: liveness-http
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health/status
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 1
  restartPolicy: Never