apiVersion: v1
kind: Service
metadata:
  labels:
    name: php-frontend-svr
  name: php-frontend-svr
spec:
  selector:
    name: frontend
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001