apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    app: nginx
spec:
  initContainers:
    - name: install
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "wget", "-O", "/work/index.html", "http://www.baidu.com"]
      volumeMounts:
        - name: workdir
          mountPath: /work
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
  volumes:
    - name: workdir
      emptyDir: {}