apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["/bin/sh", "echo", "123"]
        restartPolicy: Never
  parallelism: 1
  completions: 5