apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app-test
data:
  name: daniel
  app: cm-app-test

---

apiVersion: v1
kind: Pod
metadata:
  name: cm-app-test
  labels:
    name: cm-app-test
spec:
  containers:
    - name: cm-app-test
      image: kubeguide/tomcat-app:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: server-config
          mountPath: /data/release/config
  volumes:
    - name: server-config
      configMap:
        name: cm-app-test
        items:
          - key: app
            path: app.txt
          - key: name
            path: name.txt