apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: MTIzNDU2Cg==
  username: cmVkaXMK

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app-test
data:
  name: daniel
  app: cm-app-test

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    rack: rack-22
    cluster: test-cluster
    zone: us-est-coast
  annotations:
    build: two
    builder: john-doe
  name: project-volume-test
spec:
  containers:
    - name: myredis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: all-volume-test
          mountPath: /etc
  volumes:
    - name: all-volume-test
      projected:
        sources:
          - secret:
              name: mysecret
              items:
                - key: username
                  path: username.txt
                - key: password
                  path: password.txt
          - downwardAPI:
              items:
                - path: label.txt
                  fieldRef:
                    fieldPath: metadata.labels
                - path: annotations.txt
                  fieldRef:
                    fieldPath: metadata.annotations
          - configMap:
              name: cm-app-test
              items:
                  - key: app
                    path: app.txt
                  - key: name
                    path: name.txt