apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: MTIzNDU2Cg==
  username: cmVkaXMK

---

apiVersion: v1
kind: Pod
metadata:
  name: myredis
  labels:
    rack: rack-22
    cluster: test-cluster
    zone: us-est-coast
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: myredis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mysecret
          mountPath: /etc/foo
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
        items:
          - key: username
            path: username.txt
          - key: password
            path: password.txt
    - name: podinfo
      downwardAPI:
        items:
          - path: label.txt
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations.txt
            fieldRef:
              fieldPath: metadata.annotations
