apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-deployment
  template:
    metadata:
      labels:
        name: nginx-deployment
      name: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80