apiVersion: v1
kind: Pod
metadata:
  name: pod-flag
  labels:
    security: "S1"
    app: "nginx"
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  labels:
    flag: pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: security
                operator: In
                values:
                  - S1
          topologyKey: kubernetes.io/hostname
  containers:
    - name: redis-master
      image: kubeguide/redis-master
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
